language: node_js
node_js:
  - "7"
addons:
  firefox: "54.0"
  code_climate:
    repo_token: 77c29acf0fc4dc4578d936d2299557830033eb2ea16220f443e35db4ee7ecb5b
install:
  - npm install
before_install:
  - "npm i -g npm@latest"
  - "export DEBUG=testee:console-log"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/23a009e4a77d199f54d6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
